/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import data.CreateData;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import model.City;
import model.Community;
import model.EncounterHistory;
import model.House;
import model.Patient;
import model.PatientDirectory;
import model.Person;

/**
 *
 * @author abc
 */
public class AddJPanel extends javax.swing.JPanel {

    PatientDirectory patientList;
    List<EncounterHistory> encounterHistoryList;
    List<Community> community;
    List<City> cityList;
    List<House> houseList;
    Map<String, House> houseMap;
    
    /**
     * Creates new form AddJPanel
     */
    public AddJPanel(PatientDirectory ptd, List<EncounterHistory> ethlist) {
        initComponents();
        houseMap = new HashMap<String, House>();
        patientList = ptd;
        encounterHistoryList = ethlist;
        createTestData();
        List<String> cityTempLst = new ArrayList<String>();
        cityTempLst.add("Select");
        for(City c : cityList) {
            cityTempLst.add(c.toString());
        }
        String[] cityLst = new String[cityTempLst.size()];
        cityLst =  cityTempLst.toArray(cityLst);
        combCity.setModel(new javax.swing.DefaultComboBoxModel(cityLst));
        combCommunity.setEnabled(false);
        combHouseAdd.setEnabled(false);
        //ComboBoxModel<String> aModel = new ComboBoxModel<String>() {
        
//        combHouseAdd.setModel(new javax.swing.DefaultComboBoxModel(cityList[]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPersonInfo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblHealthPlanNo = new javax.swing.JLabel();
        txtHealthPlanNo = new javax.swing.JTextField();
        markedFieldsjLabel = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        btnLoadSampleData = new javax.swing.JButton();
        lblHouseAdd = new javax.swing.JLabel();
        combHouseAdd = new javax.swing.JComboBox<>();
        lblCommunity = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        combCommunity = new javax.swing.JComboBox<>();
        combCity = new javax.swing.JComboBox<>();

        jPanel1.setToolTipText("");

        lblPersonInfo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPersonInfo.setText("Enter Patient Information");

        lblName.setText("Name*:");
        lblName.setToolTipText("Name");
        lblName.setAlignmentX(0.5F);

        lblDob.setText("Date of Birth*:");
        lblDob.setToolTipText("");
        lblDob.setAlignmentX(0.5F);

        lblTelephone.setText("Telephone*:");
        lblTelephone.setToolTipText("");
        lblTelephone.setAlignmentX(0.5F);

        lblEmail.setText("Email Address*:");
        lblEmail.setToolTipText("");
        lblEmail.setAlignmentX(0.5F);

        lblSSN.setText("Social Security #:");
        lblSSN.setToolTipText("");
        lblSSN.setAlignmentX(0.5F);

        lblHealthPlanNo.setText("Health plan beneficiary #:");
        lblHealthPlanNo.setToolTipText("");
        lblHealthPlanNo.setAlignmentX(0.5F);

        markedFieldsjLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        markedFieldsjLabel.setText("* marked fields are mandatory");
        markedFieldsjLabel.setToolTipText("");
        markedFieldsjLabel.setAlignmentX(0.5F);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnLoadSampleData.setText("Load Sample Data");
        btnLoadSampleData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadSampleDataActionPerformed(evt);
            }
        });

        lblHouseAdd.setText("House Address:");

        lblCommunity.setText("Community:");

        lblCity.setText("City:");

        combCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combCommunityActionPerformed(evt);
            }
        });

        combCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblDob)
                            .addComponent(lblTelephone)
                            .addComponent(lblEmail)
                            .addComponent(lblSSN)
                            .addComponent(lblHealthPlanNo)
                            .addComponent(lblHouseAdd)
                            .addComponent(lblCommunity)
                            .addComponent(lblCity))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(btnSubmit)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHealthPlanNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(combCommunity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(combCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(combHouseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblPersonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnLoadSampleData))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(markedFieldsjLabel)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblPersonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadSampleData)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDob)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone)
                    .addComponent(lblTelephone))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN)
                    .addComponent(lblSSN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanNo)
                    .addComponent(txtHealthPlanNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity)
                    .addComponent(combCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(combCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseAdd)
                    .addComponent(combHouseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSubmit)
                .addGap(4, 4, 4)
                .addComponent(markedFieldsjLabel)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        Patient patient = new Patient();
        String error = "";
        error = patient.setName(txtName.getText());
        if(error == "")
            error = patient.setDob(dob.getDate());
        if(error == "")
            error = patient.setPhone(Long.valueOf(txtPhone.getText()));
        if(error == "")
            error = patient.setEmail(txtEmail.getText());
        if(error == "") {
            String Ssn = txtSSN.getText();
            if(Ssn != null && !Ssn.equals(""))
            error = patient.setSsn(Long.valueOf(Ssn));            
        }
        if(error == "")
            error = patient.setHealthPlanNumber(txtHealthPlanNo.getText());
        if(error == "")
            error = patient.setHealthPlanNumber(txtHealthPlanNo.getText());
        if(error == "") {
            String house = combHouseAdd.getSelectedItem().toString();
            House hs = houseMap.get(house);
                patient.setHouse(hs);
        }

        String message = error.equals("") ? "Person Information Saved" : error;

        JOptionPane.showMessageDialog(this, message);
        if(error.equals("")) {
            patientList.add((Patient) patient);        
            txtName.setText("");
            txtPhone.setText("");
            txtEmail.setText("");
            txtSSN.setText("");
            combCity.setSelectedItem("Select");
            combHouseAdd.setSelectedItem("Select");
            combCommunity.setSelectedItem("Select");
            combHouseAdd.setSelectedItem("Select");
            combCommunity.setSelectedItem("Select");            
            txtHealthPlanNo.setText("");
            dob.setDate(null);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnLoadSampleDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadSampleDataActionPerformed
        CreateData cd = new CreateData();
        List<Patient> plist = cd.createPatients(houseList);
        patientList.addAll(plist);
        encounterHistoryList = cd.createEncounters(patientList.getPatientList());
        System.out.println("---Param-");
        for(EncounterHistory eh : encounterHistoryList) {
            System.out.println(eh);
            System.out.println(eh.getEncounterList().get(0).getDepartment());
            System.out.println("---q12-");
        }
        JOptionPane.showMessageDialog(this, "Patient Sample Data Loaded");
    }//GEN-LAST:event_btnLoadSampleDataActionPerformed

    private void combCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combCityActionPerformed
        String cityIndex = (String) combCity.getSelectedItem();
        if(cityIndex.equals("Select") == false) {
            List<String> commTempLst = new ArrayList<String>();
            commTempLst.add("Select");
            for(Community c : community) {
                if(c.getCity().toString().equals(cityIndex)) {
                    commTempLst.add(c.toString());
                }
            }
            String[] commList = new String[commTempLst.size()];
            commList = commTempLst.toArray(commList);

            combCommunity.setModel(new javax.swing.DefaultComboBoxModel(commList));
            combCommunity.setEnabled(true);
            combHouseAdd.setEnabled(false);            
        }
        else {
            combHouseAdd.setEnabled(false);            
            combCommunity.setEnabled(false);
        }
    }//GEN-LAST:event_combCityActionPerformed

    private void combCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combCommunityActionPerformed
        String commIndex = (String) combCommunity.getSelectedItem();
        if(commIndex.equals("Select") == false) {
            List<String> houseTempLst = new ArrayList<String>();

            for(House h : houseList) {
                if(h.getCommunity().toString().equals(commIndex)) {
                    houseTempLst.add(h.toString());
                }
            }
            String[] houseList = new String[houseTempLst.size()];
            houseList = houseTempLst.toArray(houseList);

            combHouseAdd.setModel(new javax.swing.DefaultComboBoxModel(houseList));
            combHouseAdd.setEnabled(true);
        }
        else {
            combHouseAdd.setEnabled(false);            
        }
    }//GEN-LAST:event_combCommunityActionPerformed
    
    public void createTestData() {
        CreateData cd = new CreateData();
        cityList = cd.createCity();
        community = cd.createCommunity(cityList);
        houseList = cd.createHouses(community);
        for(House hs : houseList) {
            houseMap.put(hs.toString(), hs);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadSampleData;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> combCity;
    private javax.swing.JComboBox<String> combCommunity;
    private javax.swing.JComboBox<String> combHouseAdd;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHealthPlanNo;
    private javax.swing.JLabel lblHouseAdd;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonInfo;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel markedFieldsjLabel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHealthPlanNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables
}
