/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.profileapplication;

import com.mycompany.profileapplication.model.Person;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author abc
 */
public class ViewJPanel extends javax.swing.JPanel {

    Person person;
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Person person) {
        initComponents();
        this.person = person;
        displayData();
    }
    
    private void displayData() {
        txtName.setText(person.getName());
        txtAddress.setText(person.getAddress());
        txtZip.setText(person.getZip());
        txtEmail.setText(person.getEmail());
        comboCountry.setSelectedItem(person.getCountry());
        dob.setDate(person.getDob());
        txtPhone.setText(person.getPhone());
        txtFax.setText(person.getFaxNumber());
        txtSSN.setText(person.getSsn());
        txtMedicalNo.setText(person.getMedicalRecNumber());
        txtHealthPlanNo.setText(person.getHealthPlanNumber());
        txtLicenseNo.setText(person.getLicenseNumber());
        txtVin.setText(person.getVin());
        txtLicensePlate.setText(person.getLicensePlate());
        txtLinkedin.setText(person.getLinkedin());
        txtIPAddress.setText(person.getIpAddress());

        ImageIcon icon = new ImageIcon(person.getFilePath());
        lblFilePath.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateScroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblPersonInfo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        txtPhone = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalNo = new javax.swing.JTextField();
        lblMedicalNo = new javax.swing.JLabel();
        lblHealthPlanNo = new javax.swing.JLabel();
        txtLicenseNo = new javax.swing.JTextField();
        txtHealthPlanNo = new javax.swing.JTextField();
        lblLicenseNo = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblGepgraphicData = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        comboCountry = new javax.swing.JComboBox<>();
        txtLinkedin = new javax.swing.JTextField();
        lblIPAddress = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        lblVehicleIdentifier = new javax.swing.JLabel();
        lblVin = new javax.swing.JLabel();
        txtVin = new javax.swing.JTextField();
        lblLicensePlate = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblFilePath = new javax.swing.JLabel();

        CreateScroll.setMaximumSize(new java.awt.Dimension(327, 327));
        CreateScroll.setPreferredSize(new java.awt.Dimension(10, 10));

        jPanel1.setToolTipText("");

        lblPersonInfo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPersonInfo.setText("Enter Person Information");

        lblName.setText("Name*:");
        lblName.setToolTipText("Name");
        lblName.setAlignmentX(0.5F);

        lblDob.setText("Date of Birth*:");
        lblDob.setToolTipText("");
        lblDob.setAlignmentX(0.5F);

        lblTelephone.setText("Telephone*:");
        lblTelephone.setToolTipText("");
        lblTelephone.setAlignmentX(0.5F);

        lblFax.setText("Fax Number:");
        lblFax.setToolTipText("");
        lblFax.setAlignmentX(0.5F);

        lblEmail.setText("Email Address*:");
        lblEmail.setToolTipText("");
        lblEmail.setAlignmentX(0.5F);

        lblSSN.setText("Social Security #:");
        lblSSN.setToolTipText("");
        lblSSN.setAlignmentX(0.5F);

        txtMedicalNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalNoActionPerformed(evt);
            }
        });

        lblMedicalNo.setText("Medical record #:");
        lblMedicalNo.setToolTipText("");
        lblMedicalNo.setAlignmentX(0.5F);

        lblHealthPlanNo.setText("Health plan beneficiary #:");
        lblHealthPlanNo.setToolTipText("");
        lblHealthPlanNo.setAlignmentX(0.5F);

        lblLicenseNo.setText("Certificate/license #:");
        lblLicenseNo.setToolTipText("");
        lblLicenseNo.setAlignmentX(0.5F);

        lblLinkedin.setText("Linkedin:");
        lblLinkedin.setToolTipText("");
        lblLinkedin.setAlignmentX(0.5F);

        lblGepgraphicData.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblGepgraphicData.setText("Geographic Data");
        lblGepgraphicData.setToolTipText("");
        lblGepgraphicData.setAlignmentX(0.5F);

        lblAddress.setText("Address*:");
        lblAddress.setToolTipText("");
        lblAddress.setAlignmentX(0.5F);

        txtZip.setToolTipText("5-6 digit Valid Pin code");

        lblZip.setText("Zip*:");
        lblZip.setToolTipText("");
        lblZip.setAlignmentX(0.5F);

        lblCountry.setText("Country*:");
        lblCountry.setToolTipText("");
        lblCountry.setAlignmentX(0.5F);

        comboCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Country", "Africa", "Bangaldesh", "Canada", "Germany", "India", "Spain", "United Kingdom", "United States", " " }));

        lblIPAddress.setText("IP Address:");
        lblIPAddress.setToolTipText("");
        lblIPAddress.setAlignmentX(0.5F);

        lblVehicleIdentifier.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblVehicleIdentifier.setText("Vehicle Identifier");
        lblVehicleIdentifier.setToolTipText("");
        lblVehicleIdentifier.setAlignmentX(0.5F);

        lblVin.setText("Vehicle Identification #:");
        lblVin.setToolTipText("");
        lblVin.setAlignmentX(0.5F);

        txtVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVinActionPerformed(evt);
            }
        });

        lblLicensePlate.setText("License Plate #:");
        lblLicensePlate.setToolTipText("");
        lblLicensePlate.setAlignmentX(0.5F);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel1.setText("* marked fields are mandatory");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentX(0.5F);

        jLabel2.setText("Photo Uploaded:");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblPersonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblZip, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCountry, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDob, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGepgraphicData, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelephone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFax, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMedicalNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHealthPlanNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLicenseNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVehicleIdentifier, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVin, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLicensePlate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLinkedin, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIPAddress, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN)
                            .addComponent(txtMedicalNo)
                            .addComponent(txtHealthPlanNo)
                            .addComponent(txtLicenseNo)
                            .addComponent(txtVin)
                            .addComponent(txtLicensePlate)
                            .addComponent(txtLinkedin)
                            .addComponent(txtIPAddress))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblPersonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblName))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblGepgraphicData)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress)
                            .addComponent(lblAddress))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtZip)
                            .addComponent(lblZip))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboCountry)
                            .addComponent(lblCountry))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDob))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone)
                    .addComponent(lblTelephone))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFax)
                    .addComponent(lblFax))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN)
                    .addComponent(lblSSN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicalNo)
                    .addComponent(lblMedicalNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHealthPlanNo)
                    .addComponent(lblHealthPlanNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblLicenseNo))
                    .addComponent(txtLicenseNo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblVehicleIdentifier)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVin)
                    .addComponent(lblVin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLicensePlate)
                    .addComponent(lblLicensePlate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkedin)
                    .addComponent(lblLinkedin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIPAddress)
                    .addComponent(lblIPAddress))
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        CreateScroll.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(CreateScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addComponent(CreateScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicalNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalNoActionPerformed

    private void txtVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CreateScroll;
    private javax.swing.JComboBox<String> comboCountry;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFilePath;
    private javax.swing.JLabel lblGepgraphicData;
    private javax.swing.JLabel lblHealthPlanNo;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedicalNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPersonInfo;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JLabel lblVin;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthPlanNo;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtVin;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
